# Generated by Django 4.2.11 on 2024-07-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=200)),
                ('image', models.FilePathField(path='/img')),
                ('condition', models.CharField(max_length=100)),
                ('github', models.URLField(default='')),
                ('video', models.FilePathField(default='', path='/videos')),
                ('sourceCode', models.BooleanField(default=False)),
                ('demo', models.BooleanField(default=False)),
                ('readme', models.URLField(default='')),
            ],
        ),
    ]
