# Generated by Django 4.2.11 on 2024-07-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_only',
            field=models.BooleanField(default=False),
        ),
    ]
