# Generated by Django 4.2.14 on 2024-07-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=100)),
                ('championships', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'teams',
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('player_id', models.CharField(max_length=64, unique=True)),
                ('height', models.CharField(max_length=4)),
                ('weight', models.FloatField(default=0.0)),
                ('position', models.CharField(max_length=4)),
                ('jersey_number', models.IntegerField(default=None)),
                ('draft_pick', models.CharField(default=None, max_length=2)),
                ('draft_year', models.CharField(default=None, max_length=4)),
                ('draft_round', models.CharField(default=None, max_length=2)),
                ('final_year', models.CharField(blank=True, max_length=4, null=True)),
                ('college', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('career_pts_avg', models.FloatField(default=0.0)),
                ('career_reb_avg', models.FloatField(default=0.0)),
                ('career_ast_avg', models.FloatField(default=0.0)),
                ('latest_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.team')),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
