# Generated by Django 4.2.11 on 2024-07-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('country_code', models.CharField(default='US', max_length=256)),
                ('postal_code', models.CharField(max_length=5)),
                ('company_name', models.CharField(max_length=256, unique=True)),
                ('position', models.CharField(help_text='Employment title', max_length=128)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.company')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('country_code', models.CharField(default='US', max_length=256)),
                ('postal_code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(help_text='basic grouping for type of work experience', max_length=64)),
                ('description', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resume.job')),
            ],
            options={
                'db_table': 'work_experiences',
            },
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('degree', models.CharField(blank=True, choices=[('High School Diploma', 'High School'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'Phd')], max_length=64)),
                ('major', models.CharField(blank=True, max_length=64)),
                ('minor', models.CharField(blank=True, max_length=64)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.school')),
            ],
            options={
                'db_table': 'education_history',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('country_code', models.CharField(default='US', max_length=256)),
                ('postal_code', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('linkedin_url', models.URLField(max_length=256)),
                ('web_portfolio_url', models.URLField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'contacts',
                'unique_together': {('first_name', 'last_name', 'email')},
            },
        ),
    ]
